baseURL = 'https://blog.woooo.tech/'
languageCode = 'zh-CN'
title = "Reverier's Blog"
theme = "LoveIt"
languageName = "简体中文"
hasCJKLanguage = true
defaultContentLanguage = "zh-cn"

# 作者配置
[author]
  name = "Reverier-Xu"
  email = "reverier.xu@outlook.com"
  link = "https://blog.woooo.tech"

# 菜单配置
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = "<span style=\"color: #0078D6\">&gt;&gt;</span>"
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = "<span style=\"color: #0078D6\">&gt;&gt;</span>"
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = "<span style=\"color: #0078D6\">&gt;&gt;</span>"
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "friends"
    pre = "<span style=\"color: #0078D6\">&gt;&gt;</span>"
    post = ""
    name = "朋友们"
    url = "/friends"
    title = ""
  [[menu.main]]
    weight = 5
    identifier = "about"
    pre = "<span style=\"color: #0078D6\">&gt;&gt;</span>"
    post = ""
    name = "关于"
    url = "/about"
    title = ""

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
